readinglist/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/booklist/urls.py
from django.urls import path
from . import views

app_name = 'booklist'


urlpatterns = [
    path('list/', views.booklist, name='booklist-list'),
    path('userlist/', views.userlist, name='usersbooklist'),
]

readinglist/readinglist/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('list/', include('booklist.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('list_download/', views.list_download, name='list_download'),

]

urlpatterns += staticfiles_urlpatterns()

readinglist/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from booklist.models import Userfavorite
from booklist.forms import Deletebook, UserCreationFormEmail


def signup_view(request):
    form = UserCreationFormEmail()
    if request.method == 'POST':
        form = UserCreationFormEmail(request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user) 
        return redirect('account:userpage')
    else:
        form = UserCreationFormEmail()
        return render(request, 'account/signup.html', {'form':form})

@login_required()
def userpage(request):
    context = {}
    username = request.user
    userid = request.user.id
    context['username'] = username
    context['userid'] = userid
    context['deletebookform'] = Deletebook
    booklist = []

    for book in Userfavorite.objects.filter(user_id=userid):
        booklist.append(book)
        context['booklist'] = booklist

    return render(request, 'account/userpage.html', context)

def loginpage(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
        return redirect('account:userpage')
    else:
        form = AuthenticationForm()
    return render(request, 'account/loginpage.html', {'form':form})

def logoutpage(request):
    if request.method == 'POST':
        logout(request)
    return redirect('account:login')

def userrating(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        objid = request.POST.get('favoriteid')
        book = Userfavorite.objects.filter(id=objid)[0]
        book.rating = rating
        book.save()
        return redirect('account:userpage')

def deleteuserfavorite(request):
    if request.method == 'POST':
        rowid = request.POST.get('userfavoriteid')
        print("rowid is: ", rowid)
        record = Userfavorite.objects.get(id=rowid)
        record.delete()
        return redirect('account:userpage')


    

readinglist/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from booklist.models import Userfavorite
from booklist.forms import Deletebook, UserCreationFormEmail

def signup_view(request):
    form = UserCreationFormEmail()
    if request.method == 'POST':
        form = UserCreationFormEmail(request.POST)
    if form.is_valid():
        user = form.save()
        login(request, user) 
        return redirect('accounts:userpage')
    else:
        form = UserCreationFormEmail()
        return render(request, 'accounts/signup.html', {'form':form})

@login_required()
def userpage(request):
    context = {}
    username = request.user
    userid = request.user.id
    context['username'] = username
    context['userid'] = userid
    context['deletebookform'] = Deletebook
    booklist = []

    for book in Userfavorite.objects.filter(user_id=userid):
        booklist.append(book)
        context['booklist'] = booklist
    return render(request, 'accounts/userpage.html', context)

def loginpage(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
        return redirect('accounts:userpage')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/loginpage.html', {'form':form})

def logoutpage(request):
    if request.method == 'POST':
        logout(request)
    return redirect('accounts:login')

def userrating(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        objid = request.POST.get('favoriteid')
        tracking = request.POST.get('tracking')
        user = request.user
        book = Userfavorite.objects.filter(user=user).filter(id=objid)[0]
        book.rating = rating
        book.tracking = tracking
        book.save()
        return redirect('accounts:userpage')

def deleteuserfavorite(request):
    if request.method == 'POST':
        rowid = request.POST.get('userfavoriteid')
        print("rowid is: ", rowid)
        record = Userfavorite.objects.get(id=rowid)
        record.delete()
        return redirect('accounts:userpage')

readinglist/accounts/templates/accounts/loginpage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="page-content">
  <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
  </form>
  <div>
    <p>Forgot your password? Click <a href="{% url 'password_reset' %}">here</a> to reset it.</p>
  </div>
</div>
{% endblock %}

readinglist/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="page-content">
  <h1>Signup Page</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
</div>
  {% endblock %}
  

readinglist/accounts/templates/accounts/userpage.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="page-content">
  <h1>Welcome to your user page, {{ username }}</h1>
  <h2> Here is your personal reading list. </h2>
<<<<<<< HEAD
  {% for book in booklist %}
  <div class="book">
    <h2>{{ book.book.title }}, by {{ book.book.author }}.</h2>
      <h3> Tracking ID: {{ book.tracking}} </h3>
      <h3>Current Rating: {{ book.rating }} </h3>
      <form action="userrating/" method="POST">
        {% csrf_token %}
        Add/Update rating: <input type="number" max="5" min="1" required=True name="rating">
        <input type="hidden" name="favoriteid" value="{{ book.id }}">
        Add Tracking ID (optional): <input type="text" name="tracking">
        <button type="submit">Submit</button>
      </form>
      <form action="deleteuserfavorite/" method="POST">
        {% csrf_token %}
        <h2>
        <input type="hidden" name="userfavoriteid" value="{{ book.id }}">
        </h2>
        <button type="submit">Delete book</button>
      </form>
    {% endfor %}
    <h3>Want to add another book? Visit the <a href="{% url 'booklist:booklist-list' %}">List</a> page to view the entire book collection.</h3>
    <h3>Need to download your userlist with custom tracking ID's? Click <a href="{% url 'readinglist:list-download' %}">Here</a> to download a CSV file.</h3>
=======
  <div class="book">

      <table class="table">
          <thead>
            <tr>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Rating</th>
              <th scope="col">Tracking ID</th>
              <th scope="col">Submit</th>
            </tr>
          </thead>
          <tbody>
    {% for book in booklist %}
              <tr>
                <td>{{ book.book.title }}</td>
                <td>{{ book.book.author }}</td>
                <td>
                  <form action="{% url 'accounts:userrating' %}" method="POST">
                  {% csrf_token %}
                  <input type="number" max="5" min="1" required=True name="rating" value="{{book.rating}}">             
                </td>
                <td><input type="hidden" name="favoriteid" value="{{ book.id }}">
                  Add Tracking ID (optional): <input type="text" name="tracking" value="{{book.tracking}}"></td>
                <td>
                  <button type="submit">Submit</button>
                </form>
              </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    <h3>Want to add another book? Visit the <a href="{% url 'booklist:booklist-list' %}">List</a> page to view the entire book collection.</h3>
    <h3>Need to download your userlist with custom tracking ID's? Click <a href="{% url 'list_download' %}">Here</a> to download a CSV file.</h3>
>>>>>>> 5006865f81a2ed7d4584d527ff0ab7791cc414cb
  </div>
</div>
  
{% endblock %}
  