readinglist/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/booklist/urls.py
from django.urls import path
from . import views

app_name = 'booklist'


urlpatterns = [
    path('list/', views.booklist, name='booklist-list'),
    path('userlist/', views.userlist, name='usersbooklist'),
]

readinglist/readinglist/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('list/', include('booklist.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('list_download/', views.list_download, name='list_download'),

]

urlpatterns += staticfiles_urlpatterns()

readinglist/booklist/models.py
from django.db import models
from django.conf import settings

class Book(models.Model):
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    title = models.CharField(max_length=40, null=False, default="untitled")
    author = models.CharField(max_length=40, default="no author listed")
    class Meta:
        unique_together = ('title', 'author',)

    def __str__(self):
        return self.title

class Userfavorite(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name="favorite")
    rating = models.IntegerField(blank=True, null=True)
    tracking = models.CharField(max_length=30, default="N/A")





  

readinglist/booklist/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User

class Addbook(forms.Form):
    title = forms.CharField(required=True)
    author = forms.CharField(required=True)

class Adduserbook(forms.Form):
    userid = forms.IntegerField(widget=forms.HiddenInput())
    bookid = forms.IntegerField(widget=forms.HiddenInput())

class Deletebook(forms.Form):
    userfaveid = forms.IntegerField(widget=forms.HiddenInput())

class UserCreationFormEmail(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

readinglist/booklist/views.py
from django.shortcuts import render, redirect
from booklist.forms import Addbook, Adduserbook, Deletebook
from .models import Book, Userfavorite



def booklist(request):
    if request.method == 'GET':
        context = {}
        context['username'] = request.user
        context['books'] = Book.objects.all().order_by('title')
        context['userid'] = request.user.id
        form = Addbook()
        addbookform = Adduserbook()
        addbookform.userid = request.user
        context['form'] = form
        context['addbookform'] = addbookform
        context['deletebookform'] = Deletebook
        return render(request, 'booklist/booklist.html', context)
    if request.method == 'POST':
        form = Addbook(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            newbook = Book(title=title, author=author)
            newbook.save()
            return redirect( 'booklist:booklist-list')
    return redirect('booklist:booklist-list')

def userlist(request):
    if request.method == 'POST':
        form = Adduserbook(data=request.POST)
        if form.is_valid():
            userid = form.cleaned_data['userid']
            bookid = form.cleaned_data['bookid']
            entry = Userfavorite(user_id=userid, book_id=bookid,)
            entry.save()
            return redirect('/accounts/userpage/')
    









  





    

readinglist/booklist/templates/booklist/booklist.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="page-content">
  <h1>{{username}}, here's the complete list of books.</h1>
  <p>Welcome to the most awesomest collection of book titles.</p>
  <p>Go to your personal <a href="{% url 'accounts:userpage' %}">user</a> page</p>

  <div class="page-content">
  <table class="table">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Author</th>
          <th scope="col">Add to my list please</th>
        </tr>
      </thead>
      <tbody>
{% for book in books %}
          <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.author }}</td>
            <td>
                <form action="{% url 'booklist:usersbooklist' %}" method="POST">
                  {% csrf_token %}
                  <input type="hidden" name="bookid" value="{{book.id}}">
                  <input type="hidden" name="userid" value="{{userid}}">
        <button type="Submit">Add to my list</button>
              </form>
          </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>



  <!-- <div class="books">
    {% for book in books %}
    <div class="book">
      <form action="/list/userlist/" method="POST">
        {% csrf_token %}
        <input type="hidden" name="bookid" value="{{book.id}}">
        <input type="hidden" name="userid" value="{{userid}}">
      <h2>{{ book.title }}, by {{ book.author }}. <button type="Submit">Add to my list</button></h2>
    </form>
    </div> -->

    <!-- {% endfor %} -->
  </div>
  <div>
    Don't see your book? Add it below!
  </div>
  <form action="{% url 'booklist:booklist-list' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="Submit" value="Addbook">Submit</button>
</form>
</div>
</div>

  {% endblock %}
  