readinglist/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('userpage/', views.userpage, name='userpage'),
    path('login/', views.loginpage, name='login'),
    path('logout/', views.logoutpage, name='logout'),
    path('userpage/userrating/', views.userrating, name='userrating'),
    path('userpage/deleteuserfavorite/', views.deleteuserfavorite, name='deleteuserfavorite'),

]

readinglist/readinglist/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('list/', include('booklist.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('list_download/', views.list_download, name='list_download'),

]

urlpatterns += staticfiles_urlpatterns()

readinglist/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'styles.css' %}">
  <title>Booklist</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Spacebase Readlinglist App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:userpage' %}">User page</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li id="logout">
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST" id="logout">
            {% csrf_token %}
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Logout</button>
          </form>      
        </li>
      </ul>
    </div>
  </nav>
  <div class="wrapper">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

readinglist/templates/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="page-content" >
    <h1>Booklist app</h1>
    <p>The greatest of all booklist apps.</p> 
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <div class="analytics" id="recently_added">
              <h3>5 most recently added books</h3>
              {% for book in dateadded %}
              <p>{{ book.title }}</p>
              {% endfor %}
            </div>
          </div>
          <div class="col-sm">
            <div class="analytics" id="popular">
              <h3>Top 5 most popular books</h3>
              {% for book in topbooks %}
              <p>{{ book.title }}</p>
              {% endfor %}
            </div>
          </div>
          <div class="col-sm">
            <div class="analytics" id="highlyrated">
              <h3>Top 5 most highly rated books</h3>      
              {% for book in highestrated %}
              <p>{{ book }}</p>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}